Module5 task1
htmlacademy-javascript/2518717-kekstagram-1 pull request #4
Opened 2024-07-12 09:47 UTC by yarlyk

Создал модули: одна задача - один модуль. Указал экспорт и импорт

2024-07-13 13:07 UTC, ademaro commented on js/CreateUnicUser.js
> +import {getRandomInteger} from './getRandomArrayElement.js';
в именах файлов не делай больших букв, разделители — дефисы: `get-random-array-element.js`

2024-07-13 13:07 UTC, ademaro commented on js/CreateUnicUser.js
> +const CreateUnicUser = () => {
Почему с большой буквы?

2024-07-13 13:08 UTC, ademaro commented on js/CreateUnicUser.js
> +  return i;
попробуй переписать на тернарный оператор

2024-07-13 13:08 UTC, ademaro commented on js/CreateUnicUser.js
> +const CreateUnicUser = () => {
unic -> uniq

2024-07-13 13:09 UTC, ademaro commented on js/main.js
> +const DescriptionPhotos = () => ({
почему вдруг функции стали с большой буквы?))

2024-07-13 13:11 UTC, ademaro commented on js/main.js
> +const FullDescriptionRooms = () => ({
эти функции — также в моки.

Можно сделать примерно так:
```
js/mocks/utils.js
js/mocks/data.js
js/main.js
```

2024-07-13 13:11 UTC, ademaro requested changes
Жду поправок и двинем дальше, созвонимся, может?

2024-07-14 15:23 UTC, yarlyk commented on js/CreateUnicUser.js
> +const CreateUnicUser = () => {
Посчитал, что это Функция-конструктор из базового критерия Б8

2024-07-14 15:24 UTC, yarlyk commented on js/CreateUnicUser.js
> +import {getRandomInteger} from './getRandomArrayElement.js';
Да, осознал эту ошибку вчера, хотел отозвать проверку, исправить и отправить заново до понедельника. Не успел, - заметили...

2024-07-14 15:35 UTC, yarlyk commented on js/main.js
> +const FullDescriptionRooms = () => ({
Ничего не понял.

2024-07-14 15:37 UTC, yarlyk commented on js/main.js
> +const FullDescriptionRooms = () => ({
Речь идет про const FullDescriptionRooms = ()... ? Я думал эти фуекции являются основными, поэтому в майн.жс
Теперь смотрю иначе, перенесу в моки

2024-07-14 15:39 UTC, yarlyk commented on js/main.js
> +const DescriptionPhotos = () => ({
посчитал ее Функция-конструктор и по Б8 написал с большой. Исправляю

2024-07-22 14:37 UTC, yarlyk commented
все что надо было - исправил.

2025-12-07 08:50 UTC, closed without merging